version: '3.8'

services:
  # 1. AIRFLOW (Updated for Selenium/Chrome)
  airflow:
    build:
      context: .
      # MENGGUNAKAN DOCKERFILE BARU YANG ADA CHROME-NYA
      dockerfile: docker/airflow_selenium.Dockerfile
    container_name: uas_airflow
    
    # AGAR CHROME TIDAK CRASH
    shm_size: '2g'
    
    environment:
      # SequentialExecutor
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=sqlite:////opt/airflow/airflow.db
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - _AIRFLOW_DB_UPGRADE=true
      - AIRFLOW__WEBSERVER__SECRET_KEY=ini_rahasia_uas
      # minio
      # - MINIO_ENDPOINT=minio:9000
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin

      # credentials
      - AIRFLOW__WEBSERVER__RBAC=True
      - _AIRFLOW_WWW_USER_CREATE=True
      - _AIRFLOW_WWW_USER_USERNAME=admin
      - _AIRFLOW_WWW_USER_PASSWORD=admin123
      - _AIRFLOW_WWW_USER_FIRSTNAME=UAS
      - _AIRFLOW_WWW_USER_LASTNAME=Airflow
      - _AIRFLOW_WWW_USER_ROLE=Admin
      - _AIRFLOW_WWW_USER_EMAIL=uas@example.com
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./data:/opt/airflow/data
      - ./source:/opt/airflow/source
    ports:
      - "8080:8080"
    command: airflow standalone

  # 2. STREAMLIT (Tetap Sama)
  streamlit:
    build:
      context: .
      dockerfile: docker/app.Dockerfile
    container_name: uas_frontend
    environment:
      # minio
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
    volumes:
      - ./streamlit_app:/app/streamlit_app
      - ./data:/app/data
      - ./source:/app/source
      - ./models:/app/models
      - ./model_draft_mlbb.pkl:/app/model_draft_mlbb.pkl
    ports:
      - "8501:8501"
    command: streamlit run streamlit_app/main.py --server.address=0.0.0.0

  # 3. MINIO (Tetap Sama)
  minio:
    image: minio/minio:latest
    container_name: uas_minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - ./minio_data:/data